# Generated by Django 6.0.3 on 2026-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='内容哈希'),
        ),
    ]
