# Generated by Django 6.0.3 on 2026-05-18 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projects", "0002_add_personal_description_and_role_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="项目经理"),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_manager", True)),
                fields=("project",),
                name="one_manager_per_project",
            ),
        ),
    ]
