# Generated by Django 6.0.3 on 2026-06-09 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_is_draft_notification_target_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quote", "名言"),
                            ("prompt", "提示词"),
                            ("pitfall", "避坑"),
                            ("value", "价值观"),
                            ("announcement", "公告"),
                        ],
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="出处"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(blank=True, default="", verbose_name="链接"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bulletins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "走马灯公告",
                "verbose_name_plural": "走马灯公告",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
