# Generated by Django 6.0.3 on 2026-05-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0002_user_is_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.project",
                verbose_name="默认项目",
            ),
        ),
    ]
