# Generated by Django 6.0.3 on 2026-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_default_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=512, verbose_name="头像"),
        ),
    ]
