# Generated by Django 6.0.3 on 2026-05-12 04:56

import apps.kpi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0005_seed_monthly_plan_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpiscoringconfig",
            name="piece_rate_config",
            field=models.JSONField(
                default=apps.kpi.models._default_piece_rate_config,
                help_text="Code Arena 工单单价梯度、工时分级、段位阈值与保护期",
                verbose_name="工单计件配置",
            ),
        ),
    ]
