# Generated by Django 6.0.3 on 2026-05-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0006_add_piece_rate_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpisnapshot",
            name="workload_metrics",
            field=models.JSONField(blank=True, default=dict, verbose_name="工作量指标"),
        ),
    ]
