# Generated by Django 6.0.3 on 2026-06-03 09:08

import apps.kpi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_add_workload_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='员工已确认'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to', to='kpi.actionitem', verbose_name='顺延自'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='improve_note',
            field=models.TextField(blank=True, default='', verbose_name='改进措施'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='not_achieved_reason',
            field=models.CharField(blank=True, choices=[('ability', '能力/方法不足'), ('effort', '投入/主动性不够'), ('unrealistic', '目标不合理'), ('blocked', '外部阻塞'), ('reprioritized', '优先级调整')], default='', max_length=20, verbose_name='未达成归因'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='总评'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='review_dimensions',
            field=models.JSONField(blank=True, default=list, verbose_name='本任务维度'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='评分时间'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='评分人'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='维度评分'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='self_assessed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='自评时间'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='self_assessment',
            field=models.TextField(blank=True, default='', verbose_name='自评复盘'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='self_eta',
            field=models.DateField(blank=True, null=True, verbose_name='自评预计完成日期'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='self_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='自评评分'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='start_plan',
            field=models.TextField(blank=True, default='', verbose_name='执行计划'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='AI 月度小结'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='ai_summary_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI 小结生成时间'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='ai_summary_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AI 小结所用模型'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='employee_evaluation',
            field=models.TextField(blank=True, default='', verbose_name='员工评价（对员工可见）'),
        ),
        migrations.AddField(
            model_name='kpiscoringconfig',
            name='review_dimensions',
            field=models.JSONField(default=apps.kpi.models._default_review_dimensions, help_text='点评维度候选库/默认池，每项 {key,label,weight}；派发新任务时默认从此填充，之后逐任务可改', verbose_name='点评维度库'),
        ),
    ]
