# Generated by Django 6.0.3 on 2026-06-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0009_actionitem_due_date_actionitem_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='self_assessed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='自评时间'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='self_assessment',
            field=models.TextField(blank=True, default='', verbose_name='自评复盘'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='self_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='自评评分'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='AI 月度小结'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='ai_summary_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI 小结生成时间'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='ai_summary_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AI 小结所用模型'),
        ),
    ]
