# Generated by Django 6.0.3 on 2026-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0011_improvementplan_employee_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='self_eta',
            field=models.DateField(blank=True, null=True, verbose_name='自评预计完成日期'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='start_plan',
            field=models.TextField(blank=True, default='', verbose_name='执行计划'),
        ),
    ]
