# Generated by Django 6.0.3 on 2026-05-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_perms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageroute',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='是分组'),
        ),
        migrations.AddField(
            model_name='pageroute',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='page_perms.pageroute', verbose_name='父级菜单'),
        ),
    ]
