# Generated by Django 6.0.3 on 2026-05-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_issue_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="estimated_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=4.0,
                help_text="用于工单规模分级 (小型/中型/大型) 的依据,默认 4 小时",
                max_digits=8,
                verbose_name="预计工时",
            ),
        ),
    ]
