# Generated by Django 6.0.3 on 2026-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_add_estimated_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="settlement",
            field=models.JSONField(
                blank=True,
                help_text="工单标记完成时冻结的价格/工时/规则,不受后续配置修改影响",
                null=True,
                verbose_name="结算快照",
            ),
        ),
    ]
