# Generated by Django 6.0.3 on 2026-05-18 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_historicalissue_historicalissue_attachments_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalissue",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="创建时快照,后续 project.manager 变更不影响此字段",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="项目经理快照",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="创建时快照,后续 project.manager 变更不影响此字段",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_issues",
                to=settings.AUTH_USER_MODEL,
                verbose_name="项目经理快照",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("未计划", "未计划"),
                    ("待分配", "待分配"),
                    ("待确认", "待确认"),
                    ("进行中", "进行中"),
                    ("已解决", "已解决"),
                    ("已发布", "已发布"),
                    ("已关闭", "已关闭"),
                ],
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("未计划", "未计划"),
                    ("待分配", "待分配"),
                    ("待确认", "待确认"),
                    ("进行中", "进行中"),
                    ("已解决", "已解决"),
                    ("已发布", "已发布"),
                    ("已关闭", "已关闭"),
                ],
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="IssueAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("claim", "接单"),
                            ("assign", "指派"),
                            ("ai_assign", "AI分配"),
                            ("transfer", "转单"),
                            ("confirm", "确认"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="原因"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="转出方",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="issues.issue",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收方",
                    ),
                ),
            ],
            options={
                "verbose_name": "分配事件",
                "verbose_name_plural": "分配事件",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["issue", "-created_at"],
                        name="issues_issu_issue_i_3d6400_idx",
                    )
                ],
            },
        ),
    ]
