# Generated by Django 6.0.3 on 2026-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_data_status_rename_and_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='related_issues',
            field=models.JSONField(blank=True, default=list, verbose_name='关联 Issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='related_issues',
            field=models.JSONField(blank=True, default=list, verbose_name='关联 Issue'),
        ),
    ]
