# Generated by Django 6.0.3 on 2026-06-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0014_issuecomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuecomment",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "问题评论",
                "verbose_name_plural": "问题评论",
            },
        ),
    ]
