# Generated by Django 6.0.3 on 2026-06-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0016_issuechatparticipant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueassignment",
            name="action",
            field=models.CharField(
                choices=[
                    ("claim", "认领"),
                    ("assign", "指派"),
                    ("ai_assign", "AI分配"),
                    ("transfer", "转单"),
                    ("confirm", "确认"),
                ],
                max_length=20,
            ),
        ),
    ]
