# Generated by Django 6.0.3 on 2026-06-15 14:58

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_commit_gitauthoralias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='PR 编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='内容')),
                ('state', models.CharField(choices=[('open', '开放'), ('closed', '已关闭'), ('merged', '已合并')], max_length=20, verbose_name='状态')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='合并时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('base_branch', models.CharField(blank=True, max_length=255, verbose_name='目标分支')),
                ('head_branch', models.CharField(blank=True, max_length=255, verbose_name='源分支')),
                ('author_login', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('author_avatar', models.CharField(blank=True, max_length=500, verbose_name='作者头像')),
                ('html_url', models.CharField(blank=True, max_length=500, verbose_name='链接')),
                ('github_created_at', models.DateTimeField(verbose_name='GitHub 创建时间')),
                ('github_updated_at', models.DateTimeField(verbose_name='GitHub 更新时间')),
                ('synced_at', models.DateTimeField(verbose_name='同步时间')),
                ('linked_issues', models.JSONField(blank=True, default=list, verbose_name='关联 Issue')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repos.repo')),
            ],
            options={
                'verbose_name': 'Pull Request',
                'verbose_name_plural': 'Pull Requests',
                'ordering': ['-github_created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['linked_issues'], name='pr_linked_issues_gin')],
                'unique_together': {('repo', 'number')},
            },
        ),
    ]
