# Generated by Django 6.0.3 on 2026-05-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0011_data_status_rename_and_seed"),
        ("projects", "0003_projectmember_is_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="UptimeMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "method",
                    models.CharField(default="GET", max_length=10, verbose_name="方法"),
                ),
                (
                    "expected_status",
                    models.CharField(
                        default="200", max_length=50, verbose_name="期望状态码"
                    ),
                ),
                (
                    "expected_body",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="期望响应体关键字"
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=1, verbose_name="检查间隔(分钟)"
                    ),
                ),
                (
                    "timeout_secs",
                    models.PositiveIntegerField(default=20, verbose_name="超时(秒)"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "next_check_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[("up", "正常"), ("down", "宕机"), ("unknown", "未知")],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_up_at", models.DateTimeField(blank=True, null=True)),
                ("outage_started_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_incident_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="issues.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uptime_monitors",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统监控",
                "verbose_name_plural": "系统监控",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UptimeCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_at", models.DateTimeField(db_index=True)),
                ("is_up", models.BooleanField()),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="uptime.uptimemonitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控检查记录",
                "verbose_name_plural": "监控检查记录",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["monitor", "-checked_at"],
                        name="uptime_upti_monitor_828e22_idx",
                    )
                ],
            },
        ),
    ]
