# Generated by Django 6.0.3 on 2026-05-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uptime", "0002_seed_periodic_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="uptimemonitor",
            name="environment",
            field=models.CharField(
                choices=[("production", "生产"), ("staging", "预发"), ("test", "测试")],
                default="production",
                max_length=20,
                verbose_name="环境",
            ),
        ),
    ]
