# Generated by Django 6.0.3 on 2026-05-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uptime", "0003_uptimemonitor_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uptimemonitor",
            name="method",
            field=models.CharField(
                choices=[("GET", "GET")],
                default="GET",
                max_length=10,
                verbose_name="方法",
            ),
        ),
    ]
