# Generated by Django 6.0.3 on 2026-06-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectmember_is_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('engine', models.CharField(choices=[('postgres', 'PostgreSQL')], default='postgres', max_length=20, verbose_name='引擎')),
                ('ssh_host', models.CharField(blank=True, default='', help_text='留空=本地执行(备份 DevTrakr 自身)', max_length=255, verbose_name='SSH 主机')),
                ('ssh_user', models.CharField(blank=True, default='', max_length=64, verbose_name='SSH 用户')),
                ('ssh_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='SSH 端口')),
                ('docker_container', models.CharField(blank=True, default='', help_text='留空=主机上直接执行 pg_dump', max_length=128, verbose_name='DB 容器名')),
                ('db_name', models.CharField(max_length=128, verbose_name='数据库名')),
                ('db_user', models.CharField(blank=True, default='', max_length=64, verbose_name='DB 用户')),
                ('db_host', models.CharField(blank=True, default='', max_length=255, verbose_name='DB 主机(远程视角)')),
                ('db_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='DB 端口')),
                ('schedule_cron', models.CharField(blank=True, default='', help_text='5 段 cron;留空=仅手动', max_length=64, verbose_name='定时(cron)')),
                ('schedule_enabled', models.BooleanField(default=True, verbose_name='启用定时')),
                ('retention_count', models.PositiveIntegerField(default=7, help_text='保留最近 N 个成功备份;0=不限', verbose_name='保留份数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='留空表示站点级目标(如 DevTrakr 自身)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_targets', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '备份目标',
                'verbose_name_plural': '备份目标',
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', '备份中'), ('success', '成功'), ('failed', '失败')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('trigger', models.CharField(choices=[('manual', '手动'), ('scheduled', '定时')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='backups.backuptarget')),
            ],
            options={
                'verbose_name': '数据库备份',
                'verbose_name_plural': '数据库备份',
                'ordering': ['-created_at'],
            },
        ),
    ]
