# Generated by Django 6.0.3 on 2026-05-15 07:43

import apps.settings.models
import django.db.models.deletion
from django.db import migrations, models


def seed_default_project(apps, schema_editor):
    SiteSettings = apps.get_model("settings", "SiteSettings")
    Project = apps.get_model("projects", "Project")
    project_one = Project.objects.filter(pk=1).first()
    if project_one is None:
        return
    SiteSettings.objects.filter(default_project__isnull=True).update(
        default_project=project_one
    )


def unseed_default_project(apps, schema_editor):
    SiteSettings = apps.get_model("settings", "SiteSettings")
    SiteSettings.objects.update(default_project=None)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("settings", "0006_update_issue_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.project",
                verbose_name="默认项目",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="modules",
            field=models.JSONField(
                default=apps.settings.models.default_modules, verbose_name="功能模块"
            ),
        ),
        migrations.RunPython(seed_default_project, reverse_code=unseed_default_project),
    ]
