# Generated by Django 6.0.3 on 2026-06-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_issue_statuses_disabled_flag'),
        ('backups', '0002_migrate_legacy_backups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseBackup',
        ),
    ]
